###
# Test middle route
GET http://localhost:8000/
Accept: application/json

### ASK QUESTION
POST http://localhost:8000/api/query
content-type: application/json

{
    "query": "What is kevins attributes in summary less than 20 words"
}

### CLEAR CACHE
DELETE http://localhost:8000/api/cache

